AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ESPNFantasyFootballPoller:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build
      Handler: index.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Timeout: 30
      Environment:
        Variables:
          OUT_QUEUE_NAME: ESPNRelativePlays

  ESPNRelativePlaysQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ESPNRelativePlays
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "ESPNRelativePlaysDLQueue"
            - "Arn"
        maxReceiveCount: 3

  ESPNRelativePlaysDLQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ESPNRelativePlaysDL
